### ISSUE TITLE
永远拥护社会主义

### ISSUE THREAD

**Issue by XRFXRF** [killgcd/chromego#7]
你不要以为大家翻了墙会怎么样，你去看youtube简体中文评论，大家心里都心知肚明，flg这些伎俩几十年前没网络骗骗人还可以，现在这种社会了，谁还信什么神佛啊，赚钱重要！！赚钱重要！！赚钱重要！！（重要的事我说三遍！！）
而且时代早变了，邪教现在流行全能神，再不济也轮不到你flg

**Comment by Chung07** [comment]
永远拥护社会主义🇨🇳
flg分子都渗透到github上了啊……
有辨别力的人还好说，就怕一些好奇的，还没有成熟是非观的青少年，容易被利用。

**Comment by discalced** [comment]
> 你不要以为大家翻了墙会怎么样，你去看youtube简体中文评论，大家心里都心知肚明，flg这些伎俩几十年前没网络骗骗人还可以，现在这种社会了，谁还信什么神佛啊，赚钱重要！！赚钱重要！！赚钱重要！！（重要的事我说三遍！！）
> 而且时代早变了，邪教现在流行全能神，再不济也轮不到你flg

你怎么看youtube的？  我遵纪守法，看不到啊， 请指教

**Comment by XRFXRF** [comment]
> 永远拥护社会主义🇨🇳
> flg分子都渗透到github上了啊……
> 有辨别力的人还好说，就怕一些好奇的，还没有成熟是非观的青少年，容易被利用。

就是啊，墙还是很重要的

**Comment by XRFXRF** [comment]
> > 你不要以为大家翻了墙会怎么样，你去看youtube简体中文评论，大家心里都心知肚明，flg这些伎俩几十年前没网络骗骗人还可以，现在这种社会了，谁还信什么神佛啊，赚钱重要！！赚钱重要！！赚钱重要！！（重要的事我说三遍！！）
> > 而且时代早变了，邪教现在流行全能神，再不济也轮不到你flg
> 
> 你怎么看youtube的？ 我遵纪守法，看不到啊， 请指教

我在美国。。。。

**Comment by EricWong1992** [comment]
再强调一遍，墙是保护外国人的。-, -

**Comment by g18313801960** [comment]
> 
> 
> 再强调一遍，墙是保护外国人的。-, -
说的对极了，哈哈

**Comment by endingly** [comment]
> > 再强调一遍，墙是保护外国人的。-, -
> > 说的对极了，哈哈

保护外国人可还行

**Comment by JohnnyZhang92** [comment]
自个自焚不好吗忽悠别人一起

**Comment by Family-Liao** [comment]
自己练饱佢勒，傻嗨
